### ISSUE TITLE
多个页面使用ProviderWidget ，数据为空

### ISSUE THREAD

**Issue by wangfeng211** [jiang111/flutter_code#4]
我在用ProviderWidget 这个类的时候，model属性按你代码里面那样传了一个UserModel() 实例，我有2个页面用到了这个ProviderWidget，在第一级页面获取值并且赋值给UserModel的userBean，然后调用notifyListeners 方法，第一级页面都没有问题，但是到了第二级页面就发现Model中的 userBean的数据都为空了，我感觉是在第二个页面ProviderWidget 给model属性赋值，再次调用了UserModel 构造方法，把导致userBean 再次被初始化，然后数据就为空了，请问这个问题怎么解决啊

**Comment by jiang111** [comment]
多个页面共享数据，需要在根布局设置ProviderWidget，比如作为MaterialApp的父widget使用，否则无法通过provider实现跨页面共享数据

**Comment by wangfeng211** [comment]
> 多个页面共享数据，需要在根布局设置ProviderWidget，比如作为MaterialApp的父widget使用，否则无法通过provider实现跨页面共享数据

哦，明白了，非常感谢！我试一下。
