### ISSUE TITLE
请问如何实现下拉刷新序列帧？

### ISSUE THREAD

**Issue by hangYq** [jiang111/flutter_code#5]
![image](https://user-images.githubusercontent.com/23026075/122626367-c582d380-d0dc-11eb-9876-6166aa291705.png)
![image](https://user-images.githubusercontent.com/23026075/122626404-07137e80-d0dd-11eb-8b43-4034a92bd055.png)
![image](https://user-images.githubusercontent.com/23026075/122626420-15619a80-d0dd-11eb-9cf2-dbc6d85bf001.png)

这里在页面第一次启动时，loading 状态下，序列帧图片紊乱，第二次就好了

**Comment by jiang111** [comment]
试试     SchedulerBinding.instance.addPostFrameCallback((_){  _refreshIndicatorKey.currentState?.show(); } );
